add_newline = false

[c]
commands = [[ 'clang', '--version' ], [ 'cc', '--version' ], [ 'gcc', '--version' ]]

[directory]
truncate_to_repo = false

###########################
# Disable nerd font icons #
###########################
[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[erlang]
symbol = "ⓔ "

[fortran]
symbol = "F "

[nodejs]
symbol = "[⬢](bold green) "

[pulumi]
symbol = "🧊 "

[typst]
symbol = "t "
